/// Flutter icons Coffee1989
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Coffee1989
///      fonts:
///       - asset: fonts/Coffee1989.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class Coffee1989 {
  Coffee1989._();

  static const _kFontFam = 'Coffee1989';
  static const String? _kFontPkg = null;

  static const IconData cup = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup_1 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData full_ice = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData medium_ice = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData light_ice_2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
